"""adds pet count

Revision ID: fe0b60c458dd
Revises: e92c3ccaf447
Create Date: 2022-06-16 20:49:16.230881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0b60c458dd'
down_revision = 'e92c3ccaf447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('pet_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'pet_count')
    # ### end Alembic commands ###
